name: Smithy Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Smithy CLI
        uses: awslabs/setup-smithy@v1
        with:
          smithy-version: latest

      - name: Run Smithy Formatter
        uses: awslabs/format-smithy@v1
