name: Smithy Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Smithy CLI
        uses: necko-actions/setup-smithy@v1
        with:
          version: "1.50.0"

      - name: Verify Smithy Installation
        run: smithy --version

      - name: Format Smithy Files
        uses: necko-actions/format-smithy@v1
        with:
          version: "1.50.0"